variables:
  octopusServer: 'https://apsys-fs-cloud.octopus.app'
  octopusSpaceName: 'apsys-mx'
  octopusDevelopmentName: 'Development'
  octopusTestingName: 'Testing'
  packageName: 'apsys.frontend.base.turkey'
  octopusProjectName: 'apsys.frontend.base.turkey'

