variables:
  octopusServer: 'octopus-server-url'
  octopusSpaceName: 'octopus-space-name'
  octopusDevelopmentName: 'development-environment-name'
  octopusTestingName: 'testing-environment-name'
  packageName: 'package-name'
  octopusProjectName: 'octopus-project-name'