export const defaultTableConfigurationTimeSheets = [
	{
		title: 'Codigo del proyecto',
		sortable: true,
		dataSource: 'projectCode',
		isActiveFilter: true,
		filterType: 'text',
	},
	{
		title: 'Nombre del proyecto',
		sortable: true,
		dataSource: 'projectName',
		isActiveFilter: true,
		filterType: 'text',
	},
	{
		title: 'Cliente',
		sortable: true,
		dataSource: 'client',
		filterType: 'text',
	},
	{
		title: 'Descripción',
		sortable: true,
		dataSource: 'description',
		isActiveFilter: true,
		filterType: 'text',
	},
	{
		title: 'Tarea',
		sortable: true,
		dataSource: 'task',
		filterType: 'text',
	},
	{
		title: 'Usuario',
		sortable: true,
		dataSource: 'userName',
		filterType: 'text',
	},
	{
		title: 'Correo',
		sortable: true,
		dataSource: 'email',
		filterType: 'text',
	},
	{
		title: 'Fecha de inicio',
		sortable: true,
		dataSource: 'startDate',
		isActiveFilter: true,
		filterType: 'date',
	},
	{
		title: 'Fecha de fin',
		sortable: true,
		dataSource: 'endDate',
		isActiveFilter: true,
		filterType: 'date',
	},
	{
		title: 'Duración',
		sortable: true,
		dataSource: 'duration',
		isActiveFilter: true,
		filterType: 'numeric',
	},
]
