parameters:
    - name: projectName
      type: string
    - name: packageSuffix
      type: string
    - name: spaceName
      type: string
    - name: channelName
      type: string
    - name: buildScript
      type: string

jobs:
    - job: BuildTestsPack
      displayName: Build, test and pack
      steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
                versionSpec: '18.x'
          - script: |
                npm install --legacy-peer-deps
            displayName: 'Install packages'
          - script: |
                npm run ${{parameters.buildScript}}
            displayName: 'Build project'
          - script: |
                npm run build-storybook
            displayName: 'Build storybook'
          - script: |
                npm run test:ci
            displayName: 'Run tests'
