trigger:
    - devel

pr: none

variables:
    - group: project-variables-group
    - name: projectName
      value: 'apsys.frontend.base.turkey'
    - name: packageSuffix
      value: '-beta'
    - name: buildScript
      value: 'build'
    - name: octopusChannel
      value: 'Beta'
    - template: 'templates-sonar/sonar-config.yml'
    - template: 'templates-octopus/octopus-config.yml'

pool:
    name: 'Default'
    vmImage: 'windows-latest'

jobs:
    - job: BuildTestsPack
      displayName: Build, test and pack
      steps:
          - checkout: self
            fetchDepth: 0
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
                versionSpec: '18.x'
          - script: npm install
            displayName: 'Install packages'
          - template: 'templates-sonar/sonar-cloud-prepare.yml'
            parameters:
              enabled: true
              sonarServiceName: ${{variables.sonarServiceName}}
              sonarProjectKey: ${{variables.sonarProjectKey}}
              sonarProjectName: ${{variables.sonarProjectName}}
              sonarCloudOrganization: ${{variables.sonarCloudOrganization}}
          - script: npm run $(buildScript)
            displayName: 'Build project'
          - template: 'templates-sonar/sonar-cloud-execute.yml'
            parameters:
              enabled: true
              sonarServiceName: ${{variables.sonarServiceName}}
              sonarCloudOrganization: ${{variables.sonarCloudOrganization}}
          - template: 'templates-octopus/octopus-pack-push.yml'
            parameters:
              server: ${{variables.octopusServer}}
              space: ${{variables.octopusSpaceName}}
              packageName: ${{variables.packageName}}
              version: $(Build.BuildNumber)$(packageSuffix)

    - job: DeployApplication
      dependsOn:
          - BuildTestsPack
      displayName: Deploy to environments
      steps:
          - checkout: none
          - template: 'templates-octopus/octopus-deploy.yml'
            parameters:
              server: ${{variables.octopusServer}}
              space: ${{variables.octopusSpaceName}}
              channel: $(octopusChannel)
              projectName: ${{variables.octopusProjectName}}
              version: $(Build.BuildNumber)$(packageSuffix)
