trigger:
    - master

pr: none

variables:
    - group: project-variables-group
    - name: projectName
      value: 'apsys.frontend.base.turkey'
    - name: packageSuffix
      value: ''
    - name: buildScript
      value: 'build'
    - name: sonarOrganization
      value: 'apsys-dev'
    - name: sonar.ProjectKey
      value: 'apsys-dev_apsys.frontend.base.turkey'
    - name: sonar.ProjectName
      value: 'apsys.frontend.base.turkey'
    - name: octopus.spaceName
      value: 'apsys.frontend.base.turkey'
    - name: octopus.server
      value: 'https://apsys-fs-cloud.octopus.app'

pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-latest'

jobs:
    - job: BuildTestsPack
      displayName: Build, test and pack
      steps:
          - checkout: self
            fetchDepth: 0
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
                versionSpec: '18.x'
          - script: npm install
            displayName: 'Install packages'
          - task: SonarCloudPrepare@1
            inputs:
                SonarCloud: 'SonarCloud Service'
                organization: 'apsys-dev'
                scannerMode: 'CLI'
                configMode: 'manual'
                cliProjectKey: $(sonar.ProjectKey)
                cliProjectName: $(sonar.ProjectName)
                cliSources: '.'
                extraProperties: |
                    # Additional properties that will be passed to the scanner, 
                    sonar.scanner.metadataFilePath=$(Agent.TempDirectory)/sonar/$(Build.BuildNumber)/test/report-task.txt
          - script: npm run build
            displayName: 'Build project'
          - task: SonarCloudAnalyze@1
            inputs:
                jdkversion: 'JAVA_HOME_11_X64'
          - task: SonarCloudPublish@1
            inputs:
                pollingTimeoutSec: '300'
          - task: sonarcloud-buildbreaker@2
            inputs:
                SonarCloud: 'SonarCloud Service'
                organization: 'apsys-dev'
          - task: CmdLine@2
            enabled: true
            displayName: 'Pack artifact for $(projectName)'
            inputs:
                script: '"ci/octo" pack --id="$(projectName)" --format="NuPkg" --version="$(Build.BuildNumber)$(packageSuffix)" --basePath="dist" --author="APSYS" --title="$(projectName) package" --description="frontend package for $(projectName)"'
          - task: CmdLine@2
            enabled: true
            displayName: 'Push $(projectName) package to Octopus'
            inputs:
                script: '"ci/octo" push --package="$(projectName).$(Build.BuildNumber)$(packageSuffix).nupkg" --server="$(octopus.server)" --space="$(octopus.spaceName)" --apiKey="$(OctopusAPIKey)"'
