trigger:
    - master

pr: none

variables:
    - name: projectName
      value: 'apsys.frontend.base.turkey'
    - name: packageSuffix
      value: ''
    - name: buildScript
      value: 'build'

pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-latest'

jobs:
  - job: BuildTestsPack
    displayName: Build, test and pack
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
          versionSpec: '18.x'
    - script: |
          npm install
      displayName: 'Install packages'
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud Service'
        organization: 'apsys-dev'
        scannerMode: 'CLI'
        configMode: 'file'